/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author fgabr
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainStream
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ToolBar = new javax.swing.JPanel();
        ToolBarTitle = new javax.swing.JLabel();
        ToolBarSubs = new javax.swing.JLabel();
        Projetos = new javax.swing.JPanel();
        LabelProjetos = new javax.swing.JLabel();
        ProjetoIcon = new javax.swing.JLabel();
        Tarefas = new javax.swing.JPanel();
        LabelTarefas = new javax.swing.JLabel();
        TarefaIcon = new javax.swing.JLabel();
        ProjetoList = new javax.swing.JPanel();
        ScrollPanelProjetos = new javax.swing.JScrollPane();
        ProjetosList = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        EmptyTasksLists = new javax.swing.JPanel();
        taskListIcon = new javax.swing.JLabel();
        emptyListLabel = new javax.swing.JLabel();
        EmptyListSubs = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 700));

        ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        ToolBarTitle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        ToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        ToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tick/tick (4).png"))); // NOI18N
        ToolBarTitle.setText("ToDo app");

        ToolBarSubs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ToolBarSubs.setForeground(new java.awt.Color(255, 255, 255));
        ToolBarSubs.setText("Put your ideas here");
        ToolBarSubs.setToolTipText("");

        javax.swing.GroupLayout ToolBarLayout = new javax.swing.GroupLayout(ToolBar);
        ToolBar.setLayout(ToolBarLayout);
        ToolBarLayout.setHorizontalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGroup(ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ToolBarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ToolBarSubs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ToolBarLayout.setVerticalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToolBarSubs)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Projetos.setBackground(new java.awt.Color(255, 255, 255));
        Projetos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelProjetos.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        LabelProjetos.setForeground(new java.awt.Color(0, 153, 102));
        LabelProjetos.setText("Projects");

        ProjetoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add/add (5).png"))); // NOI18N

        javax.swing.GroupLayout ProjetosLayout = new javax.swing.GroupLayout(Projetos);
        Projetos.setLayout(ProjetosLayout);
        ProjetosLayout.setHorizontalGroup(
            ProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelProjetos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProjetoIcon)
                .addContainerGap())
        );
        ProjetosLayout.setVerticalGroup(
            ProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjetoIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tarefas.setBackground(new java.awt.Color(255, 255, 255));
        Tarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelTarefas.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        LabelTarefas.setForeground(new java.awt.Color(0, 153, 102));
        LabelTarefas.setText("Tasks");

        TarefaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add/add (5).png"))); // NOI18N

        javax.swing.GroupLayout TarefasLayout = new javax.swing.GroupLayout(Tarefas);
        Tarefas.setLayout(TarefasLayout);
        TarefasLayout.setHorizontalGroup(
            TarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTarefas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TarefaIcon)
                .addContainerGap())
        );
        TarefasLayout.setVerticalGroup(
            TarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TarefaIcon)
                    .addComponent(LabelTarefas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProjetoList.setBackground(new java.awt.Color(255, 255, 255));
        ProjetoList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjetosList.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        ProjetosList.setForeground(new java.awt.Color(0, 153, 102));
        ProjetosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ProjetosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProjetosList.setFixedCellHeight(30);
        ProjetosList.setSelectionBackground(new java.awt.Color(0, 153, 102));
        ScrollPanelProjetos.setViewportView(ProjetosList);

        javax.swing.GroupLayout ProjetoListLayout = new javax.swing.GroupLayout(ProjetoList);
        ProjetoList.setLayout(ProjetoListLayout);
        ProjetoListLayout.setHorizontalGroup(
            ProjetoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjetoListLayout.createSequentialGroup()
                .addComponent(ScrollPanelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProjetoListLayout.setVerticalGroup(
            ProjetoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjetoListLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollPanelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EmptyTasksLists.setBackground(new java.awt.Color(255, 255, 255));

        taskListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list/xhdpi-lists.png"))); // NOI18N

        emptyListLabel.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        emptyListLabel.setForeground(new java.awt.Color(0, 153, 102));
        emptyListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyListLabel.setText("There are no tasks");
        emptyListLabel.setToolTipText("");

        EmptyListSubs.setForeground(new java.awt.Color(102, 102, 102));
        EmptyListSubs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyListSubs.setText("Click on \"+\" to add a task");
        EmptyListSubs.setToolTipText("");

        javax.swing.GroupLayout EmptyTasksListsLayout = new javax.swing.GroupLayout(EmptyTasksLists);
        EmptyTasksLists.setLayout(EmptyTasksListsLayout);
        EmptyTasksListsLayout.setHorizontalGroup(
            EmptyTasksListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emptyListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EmptyListSubs, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        EmptyTasksListsLayout.setVerticalGroup(
            EmptyTasksListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyTasksListsLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(taskListIcon)
                .addGap(18, 18, 18)
                .addComponent(emptyListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmptyListSubs)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmptyTasksLists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmptyTasksLists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProjetoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Projetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Projetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjetoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmptyListSubs;
    private javax.swing.JPanel EmptyTasksLists;
    private javax.swing.JLabel LabelProjetos;
    private javax.swing.JLabel LabelTarefas;
    private javax.swing.JLabel ProjetoIcon;
    private javax.swing.JPanel ProjetoList;
    private javax.swing.JPanel Projetos;
    private javax.swing.JList<String> ProjetosList;
    private javax.swing.JScrollPane ScrollPanelProjetos;
    private javax.swing.JLabel TarefaIcon;
    private javax.swing.JPanel Tarefas;
    private javax.swing.JPanel ToolBar;
    private javax.swing.JLabel ToolBarSubs;
    private javax.swing.JLabel ToolBarTitle;
    private javax.swing.JLabel emptyListLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel taskListIcon;
    // End of variables declaration//GEN-END:variables
}
